language: python

python:
- "2.7"

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y closure-compiler nodejs npm
- sudo npm install -g jshint

install:
- mkdir -p ./pages_out
- pip install -r requirements-test.txt
- pip install -r requirements.txt

script: 
- python bli.py
- sh ./build.sh

after_success:
- python -m flake8 --output-file ./pages_out/flake8_report.txt
- touch ./pages_out/index.html
- mv travis-test_1.2.3-1_all.opk ./pages_out
- jshint blub.js | tee ./pages_out/jshint_report

after_failure:
- python -m flake8 --output-file ./pages_out/flake8_report.txt

before_deploy:
- find opkg-utils

deploy:
  provider: pages
  local_dir: ./pages_out
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  target_branch: gh-pages
  on:
    branch: master

