language: python

python:
- "2.7"

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y closure-compiler

install:
- mkdir -p ./Rel
- pip install -r requirements-test.txt

script: 
- python bli.py
- sh ./build.sh

after_success:
- python -m flake8 --output-file ./Rel/flake8_report.txt
- touch ./Rel/index.html
- mv travis-test_1.2.3-1_all.opk ./Rel

after_failure:
- python -m flake8 --output-file ./Rel/flake8_report.txt

before_deploy:
- find opkg-utils

deploy:
  provider: pages
  local_dir: Rel
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  target_branch: gh-pages
  on:
    branch: master

