language: python

python:
- "2.7"

install:
- mkdir -p ./Rel
- pip install -r requirements-test.txt

script: 
- python bli.py

after_success:
- python -m flake8 --output-file ./Rel/flake8_report.txt
- touch ./Rel/index.html

after_failure:
- python -m flake8 --output-file ./Rel/flake8_report.txt

deploy:
  provider: pages
  local_dir: Rel
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  target_branch: gh-pages
  on:
    branch: master

